
// Code generated by MockGen. DO NOT EDIT.
// Source: mockDemo.go

// Package mock_main is a generated GoMock package.
package main

import (
gomock "github.com/golang/mock/gomock"
reflect "reflect"
)

// MockMyInterface is a mock of MyInterface interface
type MockMyInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMyInterfaceMockRecorder
}

// MockMyInterfaceMockRecorder is the mock recorder for MockMyInterface
type MockMyInterfaceMockRecorder struct {
	mock *MockMyInterface
}

// NewMockMyInterface creates a new mock instance
func NewMockMyInterface(ctrl *gomock.Controller) *MockMyInterface {
	mock := &MockMyInterface{ctrl: ctrl}
	mock.recorder = &MockMyInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMyInterface) EXPECT() *MockMyInterfaceMockRecorder {
	return m.recorder
}

// myFunc mocks base method
func (m *MockMyInterface) myFunc() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "myFunc")
	ret0, _ := ret[0].(error)
	return ret0
}

// myFunc indicates an expected call of myFunc
func (mr *MockMyInterfaceMockRecorder) myFunc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "myFunc", reflect.TypeOf((*MockMyInterface)(nil).myFunc))
}

